### ISSUE TITLE
eps in the code is 1.03 instead of 0.03 as mention in paper

### ISSUE THREAD

**Issue by kevinchan04** [yairkit/flowstep3d#1]
Hey, it seems there is a tiny bug in your code.
https://github.com/yairkit/flowstep3d/blob/d339a8872365ba5a93cce02650ce06b64b41057a/models/flowstep3d.py#L55

Should the eps should be 0.03 not 1.03?
Is it all your released models are trained with eps 1.03?

Looking for your reply! Thank you very much.

**Comment by yairkit** [comment]
Hi @kevinchan04 ,
Thanks for your interest.

1. It is not a bug -
self.epsilon was an attempt to learn the eps, 
but if you'll run the train model you'll see that:
torch.exp(self.epsilon) -> 0 .. (the system wants to converge to a sparse correlation matrix)
That's why the hyperparameter 0.03 was added - to force  correlation matrix not to be completely sparse.

so, **effective eps is 0 + 0.03 = 0.03**


2. All models trained with this code exactly.

Hope that's answer your question.

**Comment by kevinchan04** [comment]
> Hi @kevinchan04 ,
> Thanks for your interest.
> 
> 1. It is not a bug -
>    self.epsilon was an attempt to learn the eps,
>    but if you'll run the train model you'll see that:
>    torch.exp(self.epsilon) -> 0 .. (the system wants to converge to a sparse correlation matrix)
>    That's why the hyperparameter 0.03 was added - to force  correlation matrix not to be completely sparse.
> 
> so, **effective eps is 0 + 0.03 = 0.03**
> 
> 1. All models trained with this code exactly.
> 
> Hope that's answer your question.

Thank you very much.
